# project.yml
name: IPAApp
options:
  bundleIdPrefix: com.dts
  deploymentTarget:
    iOS: 13.0
  developmentTeam: YOUR_TEAM_ID  # Bạn có thể để trống và dùng biến môi trường sau
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.dts.freefireth
    MARKETING_VERSION: 1.0
    CURRENT_PROJECT_VERSION: 1
    CODE_SIGN_STYLE: Automatic
targets:
  IPAApp:
    type: application
    platform: iOS
    sources:
      - IPAApp
      - exploit
      - kexploit
    settings:
      base:
        INFOPLIST_FILE: IPAApp/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_VERSION: 5.0
    dependencies:
      - framework: libsqlite3.tbd
      - framework: UIKit.framework
      - framework: Foundation.framework
